services:
  db:
    image: mariadb:10.11
    container_name: db_sql_bouti
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_secu
      MYSQL_DATABASE: myprof_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password_secu
    volumes:
      - mysql_data_bouti:/var/lib/mysql
    networks:
      - symfony_network

  php:
    image: ghcr.io/mihoubiboutina/projet-filrouge:latest
    container_name: app_symfony_bouti
    restart: always
    environment:
      DATABASE_URL: "mysql://symfony_user:symfony_password_secu@db:3306/myprof_db?serverVersion=10.11-mariadb&charset=utf8mb4"
      APP_ENV: prod
      APP_SECRET: un_secret_bien_garde
    depends_on:
      - db
    networks:
      - symfony_network

  web:
    image: nginx:alpine
    container_name: web_nginx_bouti
    restart: always
    ports:
      - "31414:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony_network

volumes:
  mysql_data_bouti:

networks:
  symfony_network:
    driver: bridge